name: Setup Rust toolchain

inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - name: Cache Rust toolchain artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.cargo/bin
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: ${{ runner.os }}-rust-${{ hashFiles('**/rust-toolchain.toml') }}
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Switch to latest stable Rust
      run: rustup show  # HACK: horrible hack taken from https://github.com/rust-lang/rustup/issues/1397
      shell: bash
    - name: Install SQLx
      run: cargo install sqlx-cli --no-default-features --features postgres
      shell: bash
