name: Lint commits

on:
  push:

jobs:
  lint:
    name: Lint commits
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node toolchain
        uses: ./.github/actions/setup-node
      - name: Check if commits respect the conventional commit format
        run: npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
